# Build, test and push InvenTree docker image
# This workflow runs under any of the following conditions:
#
# - Push to the master branch
# - Publish release
#
# The following actions are performed:
#
# - Check that the version number matches the current branch or tag
# - Build the InvenTree docker image
# - Run suite of unit tests against the build image
# - Push the compiled, tested image to dockerhub
name: Docker
on:
  release:
    types: [ published ]
  push:
    branches:
      - 'master'


jobs:
  publish_image:
    name: Push InvenTree web server image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Check Release tag
        run: |
          python3 ci/check_version_number.py --release --tag ${{ github.event.release.tag_name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          target: production
          build-args:
            tag=${{ github.event.release.tag_name }}
          tags: orionpt/inventree:${{ github.event.release.tag_name }}
